### ISSUE TITLE
Error for specific urls: page.evaluate: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by Equidem** [epctex/walmart-scraper#5]
Hi, while using this scraper, we have noticed that some product urls don't work, even though they are normally accessible on the Walmart website. From what we have tried, this concerns slightly under half of products.
When the scraper tries to extract them, it finishes with this error message:
`2022-12-07T23:15:13.495Z ERROR PlaywrightCrawler: Request failed and reached maximum retries. page.evaluate: NetworkError when attempting to fetch resource.
2022-12-07T23:15:13.497Z     at PlaywrightCrawler.requestHandler [as userProvidedRequestHandler] (file:///home/myuser/src/main.js:51:33)
2022-12-07T23:15:13.499Z     at /home/myuser/node_modules/@crawlee/browser/internals/browser-crawler.js:241:81
2022-12-07T23:15:13.501Z     at wrap (/home/myuser/node_modules/@apify/timeout/index.js:52:27)
2022-12-07T23:15:13.503Z     at /home/myuser/node_modules/@apify/timeout/index.js:66:7
2022-12-07T23:15:13.505Z     at /home/myuser/node_modules/@apify/timeout/index.js:65:13
2022-12-07T23:15:13.507Z     at addTimeoutToPromise (/home/myuser/node_modules/@apify/timeout/index.js:59:10)
2022-12-07T23:15:13.509Z     at PlaywrightCrawler._runRequestHandler (/home/myuser/node_modules/@crawlee/browser/internals/browser-crawler.js:241:53)
2022-12-07T23:15:13.511Z     at async PlaywrightCrawler._runRequestHandler (/home/myuser/node_modules/@crawlee/playwright/internals/playwright-crawler.js:110:9)
2022-12-07T23:15:13.513Z     at async wrap (/home/myuser/node_modules/@apify/timeout/index.js:52:21) {"id":"mrGkP1RmNpGTect","url":"https://www.walmart.com/robots.txt","method":"GET","uniqueKey":"https://walmart.com/ip/OdoBan-Original-Eucalyptus-Scent-Disinfectant-Fabric-Air-Freshener-32-fl-oz/37843462"}
`

En example of such an input would be:
`{
  "endPage": 1,
  "extendOutputFunction": "($) => {\n    const result = {};\n    // Uncomment to add a title to the output\n    // result.title = $('title').text().trim();\n\n    return result;\n}",
  "maxItems": 50,
  "outputFilterFunction": "(object) => ({...object})",
  "proxy": {
    "useApifyProxy": true
  },
  "startUrls": [
    {
      "url": "https://walmart.com/ip/Renuzit-Snuggle-Scented-Oil-Refill-for-Plug-In-Air-Fresheners-SuperFresh-Original-2-Count/298121534"
    },
    {
      "url": "https://walmart.com/ip/OdoBan-Original-Eucalyptus-Scent-Disinfectant-Fabric-Air-Freshener-32-fl-oz/37843462"
    },
    {
      "url": "https://walmart.com/ip/Raid-Max-Concentrated-Deep-Reach-Fogger-Bug-Fogger-Kills-Large-Infestations-Roaches-Ants-Flies-Mosquitoes-More-3-Pack-Net-Wt-X-2-1-oz-60-g-Total-6-3-/11046041"
    }
  ]
}
`

**Comment by Equidem** [comment]
@tugkan Of course. 
Run ID of the small example whose input I sent to you is VvFnv8KmJJynYGmod
If you want to see a run with a lot of inputs that also suffers from this error, you can check IqOuifeB3qRpbjTHc
Let me know if you need anything else :)

**Comment by tugkan** [comment]
Hey @Equidem ,

Thank you very much for sharing the run. After the investigation, we found the problem and resolved it. You can use the latest version. Sorry for the inconvenience.

Best
